### ISSUE TITLE
What are the license terms for using this code?

### ISSUE THREAD

**Issue by MoralCode** [aqilc/linkup#1]
Hello!

Just wanted to see if you had a particular set of license terms in mind for how you want people to use this code. I imagine since its public on GitHub that you intended it to be open source, but without a license the code is still legally proprietary.

https://choosealicense.com/ is a neat resource (i think from GitHub itself) on picking licenses in case that helps.

Also happy to answer questions about licensing (i know a lot, but i am not a lawyer).

**Comment by aqilc** [comment]
MIT except for my Supabase keys 😭

**Comment by MoralCode** [comment]
oh lol i hope those arent secret keys haha - happy to help you remove those from the git history if you want

**Comment by aqilc** [comment]
Yeah can we meet up IRL, I'm kind of not the best at the GIT command line so that would be awesome.
